services:
  - type: web
    name: myportfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myportfolio.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
