# Generated by Django 5.1 on 2025-02-22 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactdetail',
        ),
    ]
